#!/usr/bin/env python3
"""Generate the daily banking regulatory briefing."""

import json
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
import xml.etree.ElementTree as ET

import requests
from anthropic import Anthropic

BRIEFING_DIR = Path("briefings")
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
KAGI_API_KEY = os.getenv("KAGI_API_KEY")
KAGI_API_URL = "https://kagi.com/api/v1/search"

NEWS_SOURCES = {
    "CFPB": {"query": "Consumer Financial Protection Bureau news", "name": "Consumer Financial Protection Bureau"},
    "FDIC": {"query": "fdic news", "name": "Federal Deposit Insurance Corporation"},
    "Federal Reserve": {"query": "federalreserve news", "name": "Federal Reserve"},
    "American Banker": {"query": "americanbanker news", "name": "American Banker"},
    "OCC": {"query": "Office of the Comptroller of the Currency news", "name": "Office of the Comptroller of the Currency"},
}


def parse_published_time(result):
    """Read any publication field Kagi provides, normalizing it to UTC."""
    published = (
        result.get("published")
        or result.get("published_at")
        or result.get("date")
        or result.get("datetime")
    )
    if not published:
        return datetime.now(timezone.utc)
    try:
        value = datetime.fromisoformat(str(published).replace("Z", "+00:00"))
        return (value.replace(tzinfo=timezone.utc) if value.tzinfo is None
                else value.astimezone(timezone.utc))
    except (TypeError, ValueError):
        return datetime.now(timezone.utc)


def extract_results(payload):
    """Support the Kagi API response shape used by the API playground.

    Kagi Search returns data as an array of result objects.  Older code
    expected data.results, which silently turned every successful response
    into an empty result set.
    """
    data = payload.get("data", payload) if isinstance(payload, dict) else payload
    if isinstance(data, list):
        return data
    if isinstance(data, dict):
        for key in ("results", "news", "items"):
            if isinstance(data.get(key), list):
                return data[key]
    if isinstance(payload, dict) and isinstance(payload.get("results"), list):
        return payload["results"]
    return []


def fetch_news_kagi(max_articles=15, hours_back=24):
    """Fetch recent news from all sources using the Kagi API."""
    all_articles = []
    cutoff_time = datetime.now(timezone.utc) - timedelta(hours=hours_back)

    if not KAGI_API_KEY:
        print("ERROR: KAGI_API_KEY environment variable not set", file=sys.stderr)
        return []

    # Keep this request identical to the request generated by Kagi's API
    # playground: POST JSON to /api/v1/search with the bearer token.
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {KAGI_API_KEY}",
    }

    for source_name, source_config in NEWS_SOURCES.items():
        try:
            print(f"  Searching {source_name}...", file=sys.stderr)
            payload = {"query": source_config["query"], "workflow": "news"}
            response = requests.post(
                KAGI_API_URL, json=payload, headers=headers, timeout=30
            )
            response.raise_for_status()
            response_json = response.json()
            search_results = extract_results(response_json)

            if not search_results:
                # This makes API/schema/authentication problems visible in the
                # Actions log instead of reporting only the misleading summary.
                print(
                    f"    No results found (HTTP {response.status_code}; "
                    f"response keys: {list(response_json) if isinstance(response_json, dict) else type(response_json).__name__})",
                    file=sys.stderr,
                )
                continue

            print(f"    Found {len(search_results)} results", file=sys.stderr)
            for result in search_results[:5]:
                try:
                    headline = str(result.get("title") or result.get("name") or "").strip()
                    url = str(result.get("url") or result.get("link") or "").strip()
                    summary = str(result.get("snippet") or result.get("description") or "").strip()
                    pub_time = parse_published_time(result)

                    if pub_time < cutoff_time:
                        print(f"    Skipping old: {headline[:50]}", file=sys.stderr)
                        continue
                    if not url or not headline:
                        print("    Skipping result without a title or URL", file=sys.stderr)
                        continue

                    all_articles.append({
                        "source": source_name,
                        "headline": headline[:200],
                        "summary": (summary or headline)[:300],
                        "url": url,
                        "published": pub_time.isoformat(),
                        "description": source_config["name"],
                    })
                    print(f"    Added: {headline[:60]}...", file=sys.stderr)
                except Exception as exc:
                    print(f"    Error parsing result: {exc!r}", file=sys.stderr)
        except requests.RequestException as exc:
            print(f"  Error querying {source_name}: {exc}", file=sys.stderr)
        except (ValueError, KeyError) as exc:
            print(f"  Error reading {source_name} response: {exc}", file=sys.stderr)
        except Exception as exc:
            print(f"  Unexpected error querying {source_name}: {exc!r}", file=sys.stderr)

    all_articles.sort(key=lambda article: article["published"], reverse=True)
    unique_articles = []
    seen_urls = set()
    for article in all_articles:
        if article["url"] not in seen_urls:
            seen_urls.add(article["url"])
            unique_articles.append(article)

    print(f"\n  Total articles found: {len(unique_articles)}", file=sys.stderr)
    return unique_articles[:max_articles]


def generate_eli15_summary(article):
    client = Anthropic(api_key=ANTHROPIC_API_KEY)
    prompt = f'''You are writing a regulatory/banking news briefing for CISO- and CIO-level executives at a bank.
Assume deep familiarity with banking, IT, and cybersecurity concepts — do not define standard jargon (e.g., MFA, third-party risk, exam cycles, safety-and-soundness).
Write with the density and tone of a peer briefing, not an explainer: focus on what changed, why it's material, and what a security/technology leader should actually do or watch for.
Flag specific operational, compliance, budget, or examiner-facing implications where relevant — not generic "this could matter" statements.
If the news has second-order effects (e.g., on vendor contracts, exam prep, board reporting, incident response posture), call them out explicitly.
Keep each section to 2-4 sentences — concise, but dense with substance rather than simplified.

Article headline: {article['headline']}
Article source: {article['source']}
Article summary: {article['summary']}

Respond with ONLY this JSON:
{{"what_happened":"plain language summary", "why_it_matters":"specific impact for banking/compliance", "business_impact":"one-line impact"}}'''
    try:
        message = client.messages.create(
            model="claude-opus-4-6", max_tokens=500,
            messages=[{"role": "user", "content": prompt}],
        )
        text = message.content[0].text.replace("```json", "").replace("```", "").strip()
        return json.loads(text)
    except Exception as exc:
        print(f"Error generating summary for '{article['headline']}': {exc}", file=sys.stderr)
        return {"what_happened": article["summary"][:200], "why_it_matters": "See original article for details", "business_impact": "Review required"}


def create_markdown_briefing(articles, summaries):
    now = datetime.now()
    today = now.strftime("%Y-%m-%d")
    content = f"# Regulatory Briefing - {now.strftime('%B %d, %Y')}\n\n**Generated:** {now.strftime('%I:%M %p %Z')}\n\n---\n\n"
    for article, summary in zip(articles, summaries):
        published = datetime.fromisoformat(article["published"]).strftime("%b %d, %I:%M %p %Z")
        content += f"## {article['source']}: {article['headline']}\n\n**Published:** {published}\n\n**What happened:** {summary.get('what_happened', 'N/A')}\n\n**Why it matters:** {summary.get('why_it_matters', 'N/A')}\n\n**Business impact:** {summary.get('business_impact', 'N/A')}\n\n**Read more:** [{article['source']} article]({article['url']})\n\n---\n\n"
    sources = ", ".join(sorted({article["source"] for article in articles}))
    content += f"## Summary\n\n- **Total items:** {len(articles)}\n- **Sources:** {sources}\n- **Generated:** {datetime.now(timezone.utc).isoformat()}\n"
    briefing_file = BRIEFING_DIR / f"{today}.md"
    briefing_file.parent.mkdir(parents=True, exist_ok=True)
    briefing_file.write_text(content, encoding="utf-8")
    print(f"Briefing written to {briefing_file}")
    return briefing_file


def generate_rss_feed():
    files = sorted(BRIEFING_DIR.glob("*.md"), reverse=True)
    root = ET.Element("rss", {"version": "2.0"})
    channel = ET.SubElement(root, "channel")
    ET.SubElement(channel, "title").text = "Banking Regulatory Briefing"
    ET.SubElement(channel, "link").text = "https://github.com/filimentation/regulatory-briefing"
    ET.SubElement(channel, "description").text = "Daily ELI15 regulatory news for banking professionals"
    ET.SubElement(channel, "language").text = "en-us"
    for briefing_file in files[:10]:
        date_str = briefing_file.stem
        item = ET.SubElement(channel, "item")
        ET.SubElement(item, "title").text = f"Regulatory Briefing - {date_str}"
        ET.SubElement(item, "link").text = f"https://github.com/filimentation/regulatory-briefing/blob/main/briefings/{briefing_file.name}"
        ET.SubElement(item, "description").text = briefing_file.read_text(encoding="utf-8")[:500] + "..."
        ET.SubElement(item, "pubDate").text = datetime.strptime(date_str, "%Y-%m-%d").strftime("%a, %d %b %Y 06:00:00 +0000")
        ET.SubElement(item, "guid").text = f"briefing-{date_str}"
    ET.ElementTree(root).write(Path("feed.xml"), encoding="utf-8", xml_declaration=True)
    print("RSS feed generated: feed.xml")


def main():
    if not ANTHROPIC_API_KEY:
        print("ERROR: ANTHROPIC_API_KEY environment variable not set", file=sys.stderr)
        return 1
    if not KAGI_API_KEY:
        print("ERROR: KAGI_API_KEY environment variable not set", file=sys.stderr)
        return 1
    print("Fetching regulatory news via Kagi...")
    articles = fetch_news_kagi(max_articles=12)
    if not articles:
        print("No articles found", file=sys.stderr)
        return 1
    print(f"Found {len(articles)} articles")
    print("Generating ELI15 summaries with Claude...")
    summaries = [generate_eli15_summary(article) for article in articles]
    print("Summaries generated")
    create_markdown_briefing(articles, summaries)
    generate_rss_feed()
    print("\nBriefing complete!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
